---
stages:
- name: DEPLOY
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: commit
  properties:
  - name: CF_APP_HOSTNAME
    value: ""
  - name: CF_APP_INSTANCES
    value: "1"
  - name: ADMIN_USERNAME
    value: ${ADMIN_USERNAME}
  - name: ADMIN_PASSWORD
    value: ${ADMIN_PASSWORD}
    type: secure
  - name: CLOUDANT_db
    value: ${CLOUDANT_db}
  - name: DOCKER_EXTRACTOR_NAME
    value: "l2fprod/darkvision-extractor-master"
  - name: WATSON_API_KEY
    value: ${WATSON_API_KEY}
  - name: STT_CALLBACK_SECRET
    value: ASecret{{name}}4Dv
  - name: USE_API_CACHE
    value: ""
  - name: COS_API_KEY
    value: ${COS_API_KEY}
    type: secure
  - name: COS_INSTANCE_ID
    value: ${COS_INSTANCE_ID}
  - name: COS_ENDPOINT
    value: ${COS_ENDPOINT}
  - name: COS_BUCKET
    value: ${COS_BUCKET}
  - name: COS_PLAN
    value: "Lite"
  - name: IBMCLOUD_API_KEY
    value: ${IBMCLOUD_API_KEY}
    type: secure
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      ./.bluemix/pipeline-DEPLOY.sh
